import { phenotypeOf } from "@chimaera/game";
import type { Creature } from "@chimaera/game";
import { expressPhenotype } from "@chimaera/genetics";
import { renderCreature, toSvg } from "@chimaera/rendering";
import type { DetailLevel, PaletteMode } from "@chimaera/rendering";
import { memo, useMemo } from "react";
import { map } from "../useRanch.js";

/**
 * Generated SVG, kept across mounts.
 *
 * `useMemo` alone is not enough: the ranch grid is virtualised, so scrolling
 * unmounts a card and throws its memo away, and scrolling back re-runs the
 * geometry and re-builds the string. With 500 creatures that showed up as a
 * dropped frame on every scroll step. The cache is bounded and keyed by
 * everything that can change the picture.
 */
const svgCache = new Map<string, string>();
const SVG_CACHE_LIMIT = 400;

function cached(key: string, build: () => string): string {
  const hit = svgCache.get(key);
  if (hit !== undefined) {
    // Refresh recency: cheap, and keeps the visible herd resident.
    svgCache.delete(key);
    svgCache.set(key, hit);
    return hit;
  }
  const value = build();
  svgCache.set(key, value);
  if (svgCache.size > SVG_CACHE_LIMIT) {
    const oldest = svgCache.keys().next().value;
    if (oldest !== undefined) svgCache.delete(oldest);
  }
  return value;
}

interface Props {
  readonly creature: Creature;
  readonly mode: PaletteMode;
  readonly width?: number;
  readonly frame?: boolean;
  readonly detail?: DetailLevel;
  /** Show the recessive form for one observation, without changing the genome. */
  readonly suppressDominanceAt?: readonly string[];
}

/**
 * The drawing, on screen.
 *
 * It reuses `toSvg` rather than mirroring it as JSX components. That keeps one
 * serialiser between the ranch screen, the exported plate and (later) the
 * printed lineage certificate — three places that must never disagree about
 * what a creature looks like. The markup is generated by our own escaping
 * serialiser from game state, never from user input.
 */
export const CreatureFigure = memo(function CreatureFigure({
  creature,
  mode,
  width = 240,
  frame = true,
  detail = "full",
  suppressDominanceAt,
}: Props) {
  const suppressKey = suppressDominanceAt?.length ? suppressDominanceAt.join(",") : "";
  const svg = useMemo(() => {
    const key = `${creature.id}|${creature.name}|${mode}|${width}|${frame}|${detail}|${suppressKey}`;
    return cached(key, () => {
      // A dominance suppressor changes what the observer can see for one look,
      // so it genuinely belongs in the drawing — but it must never touch the
      // cached phenotype, because nothing about the animal has changed.
      const phenotype = suppressKey
        ? expressPhenotype(creature.genome, map, { suppressDominanceAt: suppressKey.split(",") })
        : phenotypeOf(creature, map);
      const drawing = renderCreature(phenotype, map, { mode, detail });
      return toSvg(drawing, {
        width,
        height: Math.round((width * drawing.height) / drawing.width),
        journalFrame: frame,
        idPrefix: `c-${creature.id}-${mode}`,
        title: `${creature.name}, ${creature.sex === "female" ? "female" : "male"} ${map.species.name}`,
      });
    });
  }, [creature, mode, width, frame, detail, suppressKey]);

  return <div className="figure" dangerouslySetInnerHTML={{ __html: svg }} />;
});
